### ISSUE TITLE
Spring dependencies included

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf-extras-springsecurity#1]
This project has some dependencies declared inside the pom.xml with "compile" scope.

Using a different version of Spring Framework (in my case, 3.1.2) with this project results on some classpath related exceptions at Spring initialization.

The workaround is setting Maven exclusions (http://maven.apache.org/pom.html#Exclusions) in my pom.xml but it would be nice if the dependencies were declared as "provided" in the thymeleaf-extras-springsecurity3 pom.xml, as the dialect works perfectly with Spring and Spring security 3.1.2.

**Comment by danielfernandez** [comment]
pom.xml has been cleaned in 1.0-beta2-SNAPSHOT, removing all Spring dependencies and setting all SpringSecurity dependencies to scope = 'provided'
