### ISSUE TITLE
CSRF token not being added with spring-security 3.2.0.RELEASE?

### ISSUE THREAD

**Issue by willdavidwarren** [thymeleaf/thymeleaf-extras-springsecurity#12]
I just upgraded from 3.2.0.RC2 of the spring security framework (org.springframework.security:spring-security-web and org.springframework.security:spring-security-config) to 3.2.0.RELEASE and suddenly, the csrf hidden input field on my login page is not being automatically added.

What gives? Is this an error or a change in some default setting somewhere that I overlooked?

I'm using:
- thymeleaf 2.1.2.RELEASE
- thymeleaf-extras-springsecurity3 2.1.1.RELEASE
- spring 3.2.6.RELEASE
- spring security 3.2.0.RELEASE (previously 3.2.0.RC2)

**Comment by danielfernandez** [comment]
Our tests show this support is working OK in Thymeleaf with Spring Security 3.2.0.RELEASE. It looks more like a Spring Security configuration issue. I recommend you to debug the instance of the `RequestDataValueProcessor` interface that Spring Security registers for you, in order to add CSRF support (through its `getExtraHiddenFields(...)` method).

Thymeleaf calls that method here: https://github.com/thymeleaf/thymeleaf-spring3/blob/thymeleaf-spring3-2.1.2.RELEASE/src/main/java/org/thymeleaf/spring3/processor/attr/SpringActionAttrProcessor.java#L102-103

**Comment by danielfernandez** [comment]
For the record, this other ticket https://github.com/thymeleaf/thymeleaf-spring4/issues/1 might contain the answer you need. Possible causes of the problem:
- You are using XML configuration (not Java config) and not explicitly adding the `<csrf />` tag to your configuration, as explained here: http://docs.spring.io/spring-security/site/docs/3.2.0.RELEASE/reference/htmlsingle/#csrf-configure
- You are using Java configuraiton, but not adding the `@EnableWebMvcSecurity` annotation, added in Spring Security 3.2.0 as explained in this ticket https://jira.springsource.org/browse/SEC-2436. Note this is **not** the same as `@EnableWebSecurity`.

**Comment by willdavidwarren** [comment]
Thanks for the responses @danielfernandez . To your second response, that's not it, because I already had the system set up with CSRF protection and everything working great. Literally, the only thing I changed was change the `<version>` tag in my `pom.xml` for `spring-security-config` and `spring-security-web` to `3.2.0.RELEASE` and it stopped working.

As I was just typing this response, I tried updating to `3.2.0.RELEASE` again, and also adding the `@EnableWebMvcSecurity` annotation and it worked!

So, @danielfernandez correct me if I'm wrong: when using version < 3.2.0.RELEASE of `spring-security-web` and/or `spring-security-config`, you just need the `@EnableWebSecurity`, but >= 3.2.0.RELEASE, you need `@EnableWebSecurity` AND `@EnableWebMvcSecurity`?

**Comment by danielfernandez** [comment]
To my understanding of https://jira.springsource.org/browse/SEC-2436, you need both.

Note that this `@EnableWebMvcSecurity` annotation appeared in 3.2.0, not RC2, so its creation probably modified the behaviour of `@EnableWebSecurity` and removed from it the registration of the CSRF mechanism in favour of the new annotation.
