### ISSUE TITLE
Evaluation of hasPermission with a reference to the context

### ISSUE THREAD

**Issue by rhallier** [thymeleaf/thymeleaf-extras-springsecurity#13]
Hi,
In the snippet below, #vars.expectedResult doesnt seem interpolated whereas it ($expectedResult) is in the context because rendered in the rest of the page.
This is a spring4 env.

a href="#" sec:authorize="hasPermission(#vars.expectedResult,'modification')" ...

The same expression used directly in @PreAuthorize works nicely.

What have I missed ?

**Comment by danielfernandez** [comment]
What version of Thymeleaf are you using? If you are using < 2.1.3, map entries in Spring EL could not be accessed with the `map.property` syntax, but only `map['property']`, so... could you check `hasPermission(#vars['expectedResult'],'modification')`?

**Comment by rhallier** [comment]
You're right, I'm using 2.1.2, and #vars['expectedResult'] does the trick. Thank you a lot. I maybe should be mentionned in the doc/example
