### ISSUE TITLE
TemplateProcessingException when unit testing secured thymeleaf template

### ISSUE THREAD

**Issue by azeckoski** [thymeleaf/thymeleaf-extras-springsecurity#15]
Complete details are in this SO post:
http://stackoverflow.com/questions/24999469/how-to-unit-test-a-secured-controller-which-uses-thymeleaf-without-getting-temp

Summary is that the tests fail with the following error:
testLoadRoot(ltistarter.controllers.AppControllersTest) Time elapsed: 0.648 sec <<< ERROR! org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.extras.springsecurity3.dialect.processor.AuthorizeAttrProcessor' (home:33) at org.springframework.web.context.support.WebApplicationContextUtils.getRequiredWebApplicationContext(WebApplicationContextUtils.java:84)

My code is here:
https://github.com/azeckoski/lti_starter

Some comments from the ticket suggest that there is an issue getting the WAC. The trace shows a problem in WebApplicationContextUtils:84 which is throw new IllegalStateException("No WebApplicationContext found: no ContextLoaderListener registered?"); It doesn't seem to be null (I even added a check to make sure it isn't). Looks like getRequiredWebApplicationContext() requires a root context which isn't present. It is suggested that this should not be a requirement.

Is there some sample code that shows how to write an integration test like this?

**Comment by danielfernandez** [comment]
Please note this should be fixed by #36 (for Thymeleaf 2.1) and #38 (for Thymeleaf 3.0)
