### ISSUE TITLE
hasPermission expressions always false

### ISSUE THREAD

**Issue by spacejens** [thymeleaf/thymeleaf-extras-springsecurity#17]
I am attempting to use by own custom permissions in Thymeleaf pages, using the sec:authorize attribute. However, when I try to do so they always evaluate as false. I can see from the log that org.spring.security.access.expression.DenyAllPermissionEvaluator is being used, so the false evaluation certainly seems obvious.

However, the custom permissions work with the @PreAuthorize annotations I have in my Java code. How do I configure Thymeleaf to use the same PermissionEvaluator? I am using configuration by annotations, in a project based on Spring Boot.

I saw the following quote regarding the JSP security tags, and I am not sure if it applies to the Thymeleaf security attributes as well. "Currently the authorize tag uses the WebExpressionHandler, which doesn't support the use of a PermissionEvaluator or "hasPermission()" expressions." http://forum.spring.io/forum/spring-projects/security/97058-haspermission-in-sec-authorize

My code is here on GitHub, in my GaGrOr project. I made a commit on a separate branch (thymeleaf-springsecurity) trying several variants of security expressions to present a link if the URL (backed by AccountController.java) is allowed by the user:
https://github.com/spacejens/GaGrOr/commit/cf20f41a82f34a09fd31e95f95a9fd00ddac206b

**Comment by spacejens** [comment]
It is worth noting that the sec:authorize="hasRole... works as expected, i.e. only users with the specified role see the links. So I am confused as to why the other sec:... stuff is not working. And yes, I am aware that I am quite likely doing something wrong here...

**Comment by dg-** [comment]
I can confirm this!

**Comment by dg-** [comment]
I experienced the same problem recently and it does not seem to be a bug, but expected behaviour. It is somehow related to bug #5 . As danielfernandez explained there:

> which only uses the first WebInvocationPrivilegeEvaluator instance.
> And the same happens with the ExpressionHandler instance, also mimicing the original JSP tag's behaviour.

A solution that worked for me in my case was setting the PermissionEvaluator for the first expressionHandler. Your main could look something like:

``` java
    public static void main(String[] args) throws Exception {
        final ApplicationContext ctx = new SpringApplicationBuilder(SampleMethodSecurityApplication.class).run(args);

        final Map<String, WebSecurityExpressionHandler> expressionHandlers =
                ctx.getBeansOfType(WebSecurityExpressionHandler.class);

        if(expressionHandlers.values().toArray()[0] != null)
            ((DefaultWebSecurityExpressionHandler) expressionHandlers.values().toArray()[0]).setPermissionEvaluator(new YourCustomPermissionEvaluator());
    }
```

**Comment by Edward-Shaw** [comment]
Wonderful, it worked!
But I can not find WebSecurityExpressionHandler in spring security 4, using DefaultWebSecurityExpressionHandler instead.Here is my main class:

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@SpringBootApplication
public class Application extends SpringBootServletInitializer{
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(Application.class);
    }

    public static void main(String[] args) {
        //SpringApplication.run(Application.class, args);

        final ApplicationContext ctx = SpringApplication.run(Application.class, args);

        final Map<String, DefaultWebSecurityExpressionHandler> expressionHandlers =
                ctx.getBeansOfType(DefaultWebSecurityExpressionHandler.class);

        if(expressionHandlers.values().toArray()[0] != null)
            ((DefaultWebSecurityExpressionHandler) expressionHandlers.values().toArray()[0]).setPermissionEvaluator(new MyPermissionEvaluator());
    }

}
```

**Comment by danielfernandez** [comment]
Please note versions `2.1.3.RELEASE` (for Thymeleaf 2.1) and `3.0.1.RELEASE` (for Thymeleaf 3.0) have been just published including changes in the way the `PrivilegeEvaluator` is obtained, now allowing its retrieval from an `HttpServletRequest` attribute, in order to better mimic the current (modified) behaviour of Spring Security itself.

This modifications will make Thymeleaf adopt now exactly the same behaviour as is present in the standard Spring Security view-layer libraries (for JSP).

**Comment by rricote** [comment]
Hi, @dg- and @Edward-Shaw solution worked for me in my local tomcat for develop but when I deploy the war file in wildfly 10 it doesn't work. After searching the problem i have found a solution. I post it here for anyone that have the same issue.

This class is for configure the permission evaluator in the general spring app but not in thymeleaf views:
```java
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler;
import org.springframework.security.access.expression.method.MethodSecurityExpressionHandler;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration;

@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class GlobalMethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    private final BasePermissionEvaluator permissionEvaluator;

    @Autowired
    public GlobalMethodSecurityConfig(BasePermissionEvaluator permissionEvaluator) {
        this.permissionEvaluator = permissionEvaluator;
    }

    @Override
    public MethodSecurityExpressionHandler createExpressionHandler() {
        DefaultMethodSecurityExpressionHandler handler = new DefaultMethodSecurityExpressionHandler();
        handler.setPermissionEvaluator(permissionEvaluator);
        return handler;
    }
}
```
And this is the important change. You may add the "configure(WebSecurity web)" method to add the custom Permission Evaluator in the views.
```java
@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    public void configure(WebSecurity web) throws Exception {
        DefaultWebSecurityExpressionHandler handler = new DefaultWebSecurityExpressionHandler();
        handler.setPermissionEvaluator(new BasePermissionEvaluator());
        web.expressionHandler(handler);
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        ....
}
```
I hope it serves you as well as my
