### ISSUE TITLE
hasRole conforming with new Spring Security

### ISSUE THREAD

**Issue by nelsonrosenberg-hp** [thymeleaf/thymeleaf-extras-springsecurity#26]
Will the hasRole method be updated to something similar to the new spring version as seen in this issue?

https://jira.spring.io/browse/SEC-2758

Thanks!

**Comment by danielfernandez** [comment]
Actually, this is transparent to Thymeleaf's integration package. This is a behaviour wired into Spring Security expression evaluator, on which Thymeleaf does delegate for the execution of authorization expressions like those containing the `hasRole(...)` calls.

So this works out-of-the-box as long as the version of Spring Security being used supports it.
