### ISSUE TITLE
Spring Security Expression not working in Spring Security 3.1.x

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf-extras-springsecurity#3]
Hello,

Exception below is thrown during evaluating Spring Security Expression. It's because interface  `WebSecurityExpressionHandler` is marked as deprecated and tear from type hierarchy in Spring Security 3.1.x. So it's no longer possible to find `SecurityExpressionHandler` in context based on `WebSecurityExpressionHandler.class` (`AuthUtils` line 226).

``` java
org.thymeleaf.exceptions.TemplateProcessingException: No visible WebSecurityExpressionHandler instance could be found in the application context. There must be at least one in order to support expressions in Spring Security authorization queries. (normal/admin/layout:26)
    at org.thymeleaf.extras.springsecurity3.auth.AuthUtils.getExpressionHandler(AuthUtils.java:230)
    at org.thymeleaf.extras.springsecurity3.auth.AuthUtils.authorizeUsingAccessExpression(AuthUtils.java:183)
    at org.thymeleaf.extras.springsecurity3.dialect.processor.AuthorizeAttrProcessor.isVisible(AuthorizeAttrProcessor.java:101)
    at org.thymeleaf.processor.attr.AbstractConditionalVisibilityAttrProcessor.processAttribute(AbstractConditionalVisibilityAttrProcessor.java:58)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:896)
    at org.thymeleaf.dom.Node.processNode(Node.java:858)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at ... 
```

**Comment by danielfernandez** [comment]
Hi,

Being deprecated is not a problem for finding such interface. This thymeleaf module still uses that interface for compatibility reasons with Spring Security 3.0.x.

Could it be that you are not declaring a SpringSecurity expression handler? this is not done by default -- you have to tell Spring Security you want one. You can do this in two different ways:

1st, by adding `use-expressions="true"` to your `<http>` configuration tag, like you can see in Thymeleaf's SpringSecurity example application: https://github.com/thymeleaf/thymeleafexamples-springsecurity/blob/thymeleafexamples-springsecurity-20121017/src/main/webapp/WEB-INF/applicationContext-security.xml#L20

2nd, by manually creating an instance of an expression handler (only the _Default_ implementation is provided), like:

``` xml
<bean id="webexpressionHandler" class="org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler" /> 
```

Also see this thread at StackOverflow: http://stackoverflow.com/questions/11594104/spring-security-no-visible-websecurityexpressionhandler-instance-could-be-foun

**Comment by kreuzman** [comment]
Hi,

I'm sure that I declaring expression handler (by the 1sr provided example, I also using spring security expressions in application with @PreAuthorized annotation and it works). 

I also check that I have this handler in context. Problem is in place I described because `org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler` no longer implements `org.springframework.security.web.access.expression.WebSecurityExpressionHandler` so `ctx.getBeansOfType(WebSecurityExpressionHandler.class)` method can't find `DefaultWebSecurityExpressionHandler` even if it's in context. This change in spring security API happend from version 3.0.x -> 3.1.x unfortunately.

Regards
Michal

**Comment by danielfernandez** [comment]
Hmmm... maybe they made `DefaultWebSecurityExpressionHandler` not implement `WebSecurityExpressionHandler` by error in Spring Security 3.1.0?

I cannot access javadoc API for 3.1.0, but both in 3.1.1.RELEASE http://static.springsource.org/spring-security/site/docs/3.1.1.RELEASE/apidocs/org/springframework/security/web/access/expression/DefaultWebSecurityExpressionHandler.html and 3.1.3.RELEASE http://static.springsource.org/spring-security/site/docs/3.1.3.RELEASE/apidocs/org/springframework/security/web/access/expression/DefaultWebSecurityExpressionHandler.html that class implements the required interface correctly...

**Comment by kreuzman** [comment]
Ahhh....you are right it's just mistake in Spring Security 3.1.0. I missed that one. Thank you very much for helping and solving not your bug/problem :-)
