### ISSUE TITLE
Which is correct namespace ?

### ISSUE THREAD

**Issue by kazuki43zoo** [thymeleaf/thymeleaf-extras-springsecurity#33]
Hi, thymeleaf developer team.

I have one question.

Which is correct namespace ?

``` html
<html xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/extras/spring-security">
```

or 

``` html
<html xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">
```

or

other ...

**Comment by ultraq** [comment]
The namespace for both Spring 3 and 4 versions of this dialect is `http://www.thymeleaf.org/extras/spring-security`

Getting the namespace incorrect won't impact processing of your template.  It might however impact your IDE when it comes to things like suggestions/auto-completion in your templates.

**Comment by kazuki43zoo** [comment]
Hi @ultraq , Thanks for answer !!!

**Comment by JavaWebinar** [comment]
It would be nice to place namespace into description 
http://www.thymeleaf.org/doc/articles/springsecurity.html
It save some developers time.
