### ISSUE TITLE
Does not work with Spring 3.1

### ISSUE THREAD

**Issue by simonemasoni** [thymeleaf/thymeleaf-extras-springsecurity#4]
The interface WebSecurityExpressionHandler was deprecated and the new interface SecurityExpressionHandler was introduced instead.

So the method AuthUtils.getExpressionHandler always throws TemplateProcessingException.

**Comment by danielfernandez** [comment]
This is a Spring Security 3.1.0 issue. Use 3.1.1 or newer and you should be fine.

See this other issue ticket: https://github.com/thymeleaf/thymeleaf-extras-springsecurity3/issues/3
