### ISSUE TITLE
How can I get authentication exception message in login page?

### ISSUE THREAD

**Issue by lmtoo** [thymeleaf/thymeleaf-extras-springsecurity#41]

**Comment by danielfernandez** [comment]
There are several ways. In the `thymeleafexamples-springsecurity` example application you can see how a redirect to a specific controller is performed in the case of a login error: https://github.com/thymeleaf/thymeleafexamples-springsecurity/blob/380d5143908f61a986a5d37601fab8c397d892b3/src/main/java/thymeleafexamples/springsecurity/security/SpringSecurityConfig.java#L43-L45 and then in that controller a model attribute is set that is then read from the template: https://github.com/thymeleaf/thymeleafexamples-springsecurity/blob/380d5143908f61a986a5d37601fab8c397d892b3/src/main/java/thymeleafexamples/springsecurity/web/controller/MainController.java#L53-L58
