### ISSUE TITLE
Dialect is not registering its processors for text modes (JAVASCRIPT, CSS, TEXT), 

### ISSUE THREAD

**Issue by yglodt** [thymeleaf/thymeleaf-extras-springsecurity#42]
```
<script type="text/javascript" th:inline="javascript">

    /*[# sec:authorize="hasRole('ROLE_ADMIN')"]*/
        document.writeln("You are admin.");
    /*[/]*/

</script>
```

This example is unfortunately not working. According to @danielfernandez it could be because the processors are not registered for text modes.

Related stackoverflow.com-question:
[Use Spring Security in Thymeleaf escaped expressions in JavaScript](http://stackoverflow.com/questions/41434231/use-spring-security-in-thymeleaf-escaped-expressions-in-javascript)

**Comment by danielfernandez** [comment]
Already in `3.0.2-SNAPSHOT`

**Comment by danielfernandez** [comment]
Please note versions `3.0.2.RELEASE` of `thymeleaf-extras-springsecurity3` and `thymeleaf-extras-springsecurity4` have just been published.

**Comment by yglodt** [comment]
Thanks !

**Comment by 0nebean** [comment]
i got same situation,but i use 'spring boot 1.5.12.RELEASE' with servlet 3.0,
