### ISSUE TITLE
sec:authorize="hasRole('ROLE_ADMIN')" is not working

### ISSUE THREAD

**Issue by hongxf1990** [thymeleaf/thymeleaf-extras-springsecurity#45]
I am using thymeleaf-extras-springsecurity4  / 3.0.2.RELEASE.  sec:authentication="name" and sec:authentication="principal.authorities" work, but sec:authorize="hasRole('ROLE_ADMIN')" is not working.
I am sure user has role ROLE_ADMIN, because I can print it. Can you test it?

**Comment by danielfernandez** [comment]
Hello @hongxf1990 . Yours is almost exactly the same as one of the authorisation scenarios showcased in the `thymeleafexamples-springsecurity` example application (see https://github.com/thymeleaf/thymeleafexamples-springsecurity).

If you are not using Spring Boot, could you please check that your Spring Security configuration actually has the same structure as the one seen in that application?: two configurations, Spring Security being part of the *root* one, etc…

If you are using Spring Boot, your security configuration also should have a very specific shape, defined on a class of its own extending a specific adapter (please refer to Spring Boot's documentation for details)

**Comment by hongxf1990** [comment]
@danielfernandez 
Thank you vary much for your answer. I have downloaded that application and test it. Work well. After making a comparison, I upgrade thymeleaf-spring4 to 3.0.3.RELEASE. It works,

**Comment by Karan2007** [comment]
notice head declare
<html xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/extras/spring-security">
