### ISSUE TITLE
sec:authorize with hasPermission and sec:authorize-acl is always false

### ISSUE THREAD

**Issue by hasancansaral** [thymeleaf/thymeleaf-extras-springsecurity#48]
I believe [this](https://github.com/thymeleaf/thymeleaf-extras-springsecurity/issues/17) still is an issue. I have configured Spring Security ACLs properly and can use them with my `@RestController` methods successfully. However, I am having a problem when using `sec:authorize` and `sec:authorize-acl`.

`sec:authorize="hasPermission('id', 'type', 'ADMINISTRATION')"`

results in:

`2017-05-16 11:06:31.407  WARN 11069 --- [nio-9000-exec-1] o.s.s.a.e.DenyAllPermissionEvaluator     : Denying user someusername permission 'ADMINISTRATION' on object with Id 'id'`

As you can see it is evaluated by `DenyAllPermissionEvaluator`, whereas I do have a `AclPermissionEvaluator` in my context that I can use on other `@RestController` methods.

Regarding the solution described [here](https://github.com/thymeleaf/thymeleaf-extras-springsecurity/issues/17), this method shows me that there are no `DefaultWebSecurityExpressionHandler`s configured in the context:

```
@PostConstruct
    private void configureDefaultPermissionEvaluator(){

        Map<String, DefaultWebSecurityExpressionHandler> expressionHandlers = context.getBeansOfType(DefaultWebSecurityExpressionHandler.class);

        if(expressionHandlers.values().toArray().length > 0){
            ((DefaultWebSecurityExpressionHandler) expressionHandlers.values().toArray()[0]).setPermissionEvaluator(permissionEvaluator);
        } else {
            ((DefaultWebSecurityExpressionHandler) expressionHandlers.values().toArray()[0]).setPermissionEvaluator(permissionEvaluator);
        }

        ((DefaultWebSecurityExpressionHandler) expressionHandlers.values().toArray()[0]).setPermissionEvaluator(permissionEvaluator);
    }
```
and it doesn't help or make any difference to configure one as such:

```
@Bean
    public DefaultWebSecurityExpressionHandler handler(){
        DefaultWebSecurityExpressionHandler handler = new DefaultWebSecurityExpressionHandler();
        handler.setPermissionEvaluator(permissionEvaluator);
        return handler;
    }
```
When I try to use `sec:authorize-acl` expression, it is always evaluated to false, without any explanation in logs (level set to `DEBUG` too). I don't even see the log produced by the permission evaluator, nor something that should be produced by `AclAuthUtils.java` such as:

```
if (logger.isTraceEnabled()) {
                logger.trace("[THYMELEAF][{}] Checked authorization using Access Control List for user \"{}\". " +
                        "Domain object is of class \"{}\" and permissions are \"{}\". Access is DENIED.",
                        new Object[] {TemplateEngine.threadIndex(), authentication.getName(),
                                domainObject.getClass().getName(), permissions});
            }
```

I believe the latter issue has something to do with my `AclPermissionEvalutor` not being used as well. Any help on this? Happy to provide further configuration details!

**Comment by danielfernandez** [comment]
@hasancansaral thanks. Could you please confirm if this is still an issue for you, or if you were finally able to fix it?

**Comment by hasancansaral** [comment]
@danielfernandez I was able to fix it, it was due to a misconfiguration of ACLs. Thanks for the follow up.

**Comment by pouyakhoshkhoo** [comment]
> @danielfernandez I was able to fix it, it was due to a misconfiguration of ACLs. Thanks for the follow up.

Hi, How you fix this issue? I search it for two days and nothing found
