### ISSUE TITLE
springboot support

### ISSUE THREAD

**Issue by crater9893** [thymeleaf/thymeleaf-extras-springsecurity#49]
springboot support does not work, is there any plans for this?

**Comment by danielfernandez** [comment]
Could you please be more specific?

What exactly is not working for you?
What do you do in order to reproduce the issue?
Which version of Spring Boot are you using? 
Which version of Thymeleaf?

Thanks

**Comment by danielfernandez** [comment]
Closing due to user inactivity and lack of detail.
