### ISSUE TITLE
Use Thymeleaf 3 ，SpringSecurityDialect can't work #10151

### ISSUE THREAD

**Issue by helloworldtang** [thymeleaf/thymeleaf-extras-springsecurity#50]
pom.xml add:

<thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
<thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
spring boot version:1.5.6.RELEASE
according :https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#howto-use-thymeleaf-3

        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
but SpringSecurityDialect not work:
html:

···html

This content is only shown to authenticated users.

welcome:name!

    <div sec:authorize="hasAnyRole('ADMIN')">
        This content is only shown to administrators.
    </div>
    <br/>
    <div sec:authorize="hasAnyRole('USER')">
        This content is only shown to users.
    </div>
    <br/>
    <div sec:authorize="isAnonymous()">
        This content is only shown to anonymous.
    </div>

del 

<properties>
    <thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
    <thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
</properties>

it works.

why?
https://github.com/spring-projects/spring-boot/issues/10151

**Comment by danielfernandez** [comment]
If you change the version of Thymeleaf to 3.0 in Spring Boot, you also need to use a Thymeleaf 3.0-compatible version of the Spring Security integration. The current version of this branch is `3.0.2.RELEASE`. So you'd need to have:

```xml
<thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
<thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
<thymeleaf-extras-springsecurity4.version>3.0.2.RELEASE</thymeleaf-extras-springsecurity4.version>
```

Also note that the Thymeleaf core is already in `3.0.7.RELEASE`, so I would recommend upgrading your Thymeleaf core version to that value (for `thymeleaf.version` only, not the Spring Security extension).

**Comment by helloworldtang** [comment]
Thank you,  @danielfernandez 

It works.

```xml
    <properties>
        <thymeleaf.version>3.0.7.RELEASE</thymeleaf.version>
        <thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
        <thymeleaf-extras-springsecurity4.version>3.0.2.RELEASE</thymeleaf-extras-springsecurity4.version>
    </properties>


```

my side project as a reference
https://github.com/helloworldtang/sns-todo

**Comment by agbottan** [comment]
This thread solved the same problem for me too. Thank you all.

**Comment by adnanmerrakchi** [comment]
thaaaaaaanks bro! i always have problem of version compatibilty between thymeleaf and spring.
