### ISSUE TITLE
Haven't released the thymeleaf-extras-springsecurity5 dependency yet?

### ISSUE THREAD

**Issue by FirstJavaMaster** [thymeleaf/thymeleaf-extras-springsecurity#58]
I created a new project that uses `springboot 2.0.5.RELEASE` and its associated `spring-boot-starter-security` and `spring-boot-starter-thymeleaf`. Just like this:

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
```

I want to display the user name that is currently logged in on the thymeleaf-based html page. According to the information I found, I should add the following content to the html page 
```
<span sec:authentication="name">Bob</ Span>
```

However, after opening the corresponding page, the `sec:authentication` tag displayed in the navigation console is not parsed correctly, because it is still "the original look".

![image](https://user-images.githubusercontent.com/22362110/46067038-710acd80-c1a8-11e8-93b8-7536c3b6f097.png)

I found that I should add `thymeleaf-extras-springsecurity X` to the `pom.xml` file. But I can only get the `thymeleaf-extras-springsecurity4` dependency, not `thymeleaf-extras-springsecurity5` Dependence. 
There are no search results in the central maven repository, and when I use
```
<dependency>
    <groupId>org.thymeleaf.extras</groupId>
    <artifactId>thymeleaf-extras-springsecurity4</artifactId>
    <version>3.0.3-SNAPSHOT</version>
</dependency>
```
or
```
<dependency>
    <groupId>org.thymeleaf.extras</groupId>
    <artifactId>thymeleaf-extras-springsecurity4</artifactId>
    <version>3.0.2.RELEASE</version>
</dependency>
```
can't download dependencies.

So, what should I do now to make my page display the username?

**Comment by danielfernandez** [comment]
Please note that `thymeleaf-extras-springsecurity5` (version `3.0.3.RELEASE`) has just been published.

**Comment by FirstJavaMaster** [comment]
Nice!!!
