### ISSUE TITLE
Plugin not working out of the box..throws NoClassDefFoundError for a Spring Interface

### ISSUE THREAD

**Issue by prashant2402** [thymeleaf/thymeleaf-extras-springsecurity#6]
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/acls/model/NotFoundException
    at org.thymeleaf.extras.springsecurity3.dialect.SpringSecurityDialect.getAdditionalExpressionObjects(SpringSecurityDialect.java:117) [thymeleaf-extras-springsecurity3-2.0.0.jar:]

My setup is Spring 3.1.1. MVC + Thymeleaf + Spring standard dialect + Spring3Sec extras
When I try to open the home page, I get the above exception. I cant find any of 'acls' package in Spring3.1.1 jar but why are those still used in Thymeleaf extras?

Please advise.

Regards

Prash

**Comment by ultraq** [comment]
Does your setup include Spring Security 3.x as well?  I took a look at this project's pom file, and it lists Spring Security, but as a 'provided' scope, so you have to add Spring Security to your project dependencies yourself (it's also listed as a requirement in the readme file).

**Comment by prashant2402** [comment]
Yeah but not all of them. What is missing is 'spring-security-acl' but I got all other Spring security dependencies.
I haven't excluded 'spring-security-acl' from other deps. I use Spring roo so I believe it had installed all the required security jars.

Might be worth mentioning this dependency explicity in readme file as its not part of the usual spring security stack

**Comment by exp6** [comment]
I had the same issue with spring security also. The solution I've found was to down-grade the version of this to 3.1.3.RELEASE, since i've been using 3.1.4.RELEASE. 

Might be some bug on the new version of extra thymeleaf security that must use the org.springframework.security.acls.model.NotFoundException and the 3.1.4.RELEASE version of spring security doesn't keep this anymore.

I hope this may clarify more the troubleshooting.

**Comment by danielfernandez** [comment]
Please note the the acl dependency was already removed in thymeleaf-extras-springsecurity3 version 2.0.1. See https://github.com/thymeleaf/thymeleaf-extras-springsecurity3/issues/9
