### ISSUE TITLE
Bug in documentation <div sec:authorize="hasRole('ROLE_ADMIN')">

### ISSUE THREAD

**Issue by tomas-laubr-smart-software** [thymeleaf/thymeleaf-extras-springsecurity#76]
In the README.markdown I can see an example:

`<div sec:authorize="hasRole('ROLE_ADMIN')">`

Shouldn't it be rather

`<div sec:authorize="hasRole('ADMIN')">`

?

**Comment by ultraq** [comment]
It'll depend on what you've named your roles.  Role names are strings that you get to choose, and some people will choose to prefix their roles with `ROLE_`, others might not.  The readme is at least consistent in its use of role names and does include some examples like:

```html
<div th:if="${#authorization.expression('hasRole(''ROLE_ADMIN'')')}">
  This will only be displayed if authenticated user has role ROLE_ADMIN.
</div>
```

Which further enforces that the intended name, for the example anyway, is `ROLE_ADMIN`.
