### ISSUE TITLE
Provide a release to fix security vulnerability

### ISSUE THREAD

**Issue by OmarHawk** [thymeleaf/thymeleaf-extras-springsecurity#81]
Hi,

would be nice to get a new release for issue #69  so that we can get rid of the reported vulnerability in our products. Of course, we don't actually have code in there that produces the vulnerability, but unfortunately, the static code analysis tool we are using is not clever enough to detect that, therefore reporting the vulnerability as warning - and that one bugs us a lot.

Best regards

**Comment by OrangeDog** [comment]
@danielfernandez is there some blocker here?
