### ISSUE TITLE
Spring 6.0 is not detected when using JPMS

### ISSUE THREAD

**Issue by craigcondit** [thymeleaf/thymeleaf-extras-springsecurity#85]
When JPMS is in use, SpringVersion.getVersion() returns null. This prevents thymeleaf-extras-springsecurity6 from detecting Spring Framework 6.

**Comment by rburgst** [comment]
Is there going to be support for spring security 6? The fact that this MR is not being reviewed makes me question that.

**Comment by danielfernandez** [comment]
Closed by thymeleaf/thymeleaf@4515c09
