### ISSUE TITLE
Dependency on spring-security-acl, even when not using ACLs

### ISSUE THREAD

**Issue by habuma** [thymeleaf/thymeleaf-extras-springsecurity#9]
For a very simple (and most common) Spring Security needs, ACLs are not required nor used. But when using Thymeleaf's Spring Security dialect, I get a ClassNotFoundException for "org/springframework/security/acls/domain/PermissionFactory" if spring-security-acl is not in the classpath.

The specific line in the template that triggers this is:

```
<div th:text="${#authentication.name}">name</div>
```

I shouldn't have to add spring-security-acl to a project just so that this template line will work.

**Comment by danielfernandez** [comment]
Version 2.0.1 just been released. Includes this fix.
